export const ACCESS_TOKEN =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjc4LCJyb2xlSWQiOjgsImNvbXBhbnlJZCI6MTAwMDQsImV4cCI6MTgwNjczMTU1MCwiaWF0IjoxNzgwODExNTUwLCJpc3MiOiJTYWxlU2Vuc2UifQ.oMZJkGGzUUG0ouELXQxCbMbB7pAqYGnnnXATlQseZcA";

export const customerInfo = {
  id: 19893,
  serial: 100001,
  availableAdvance: 0,
  saleArea: {
    id: 68,
    name: "Natore Sadar",
    areaTypeId: 23,
    areaType: {
      id: 0,
      rank: 0,
      name: "",
      createdTime: 0,
      lastUpdatedTime: 0,
    },
    parentAreaId: 67,
    createdTime: 1780810925843,
    lastUpdatedTime: 0,
  },
  category: {
    id: 12,
    name: "Poultry & Hatchery",
    description: "Poultry & Hatchery",
    totalCustomers: 0,
    createdTime: 1780810401871,
    lastUpdatedTime: 1780810990491,
  },
  businessName: "Natore Poultry & Hatchery Complex",
  ownerName: "MD Zakir",
  code: "1029012",
  phone: "01734520260",
  email: "",
  address: "Natore Sadar",
  businessRole: "H",
  geoLocation: {
    lat: 0,
    long: 0,
  },
  categoryId: 12,
  saleAreaId: 68,
  isActive: true,
  createdTime: 1780811036903,
  lastUpdatedTime: 0,
};

export const products = [
  {
    serial: 100001,
    id: 136,
    code: "CAT-001",
    name: "Premium Cattle Feed",
    generic: "",
    description: "",
    categoryId: 27,
    imageUrl:
      "https://api.salesense.logiqbits.com/files/20260607/SQSahVMGzmGcISzilTQRvMzOXsovoRdgUPwMIjQwachvJzKtuyHhBIKaPWuXKflSqizMDtgfWfdyqrHM.png",
    isBlocked: false,
    baseUnit: "kg",
    type: "G",
    vatRate: 0,
    category: {
      id: 27,
      name: "Cattle",
      description: "Cattle",
      parentId: null,
      createdTime: 1780810120244,
      lastUpdatedTime: 0,
    },
    variants: [
      {
        id: 151,
        productId: 136,
        sku: "CAT-001",
        name: "Premium Cattle Feed",
        unit: "KG",
        unitSize: 1,
        baseUnitSize: 50,
        distributorPrice: 4800,
        retailerPrice: 4800,
        consumerPrice: 4800,
        isActive: true,
        isDefault: false,
        createdTime: 1780810190379,
        lastUpdatedTime: 0,
      },
    ],
    secondaryUnits: [],
    createdTime: 1780810142823,
    lastUpdatedTime: 1780810434891,
  },
  {
    serial: 100002,
    id: 137,
    code: "CAT-002",
    name: "Cattle Pellet Mix",
    generic: "",
    description: "",
    categoryId: 27,
    imageUrl:
      "https://api.salesense.logiqbits.com/files/20260607/gFQWOzdlNwjrAXUeDViXSwQEhjcmYmxgMrISgGdfSMlReCgAVcujJHPeAEuCpTXpZiwLTOgPLpwYuMve.png",
    isBlocked: false,
    baseUnit: "kg",
    type: "G",
    vatRate: 0,
    category: {
      id: 27,
      name: "Cattle",
      description: "Cattle",
      parentId: null,
      createdTime: 1780810120244,
      lastUpdatedTime: 0,
    },
    variants: [
      {
        id: 152,
        productId: 137,
        sku: "CAT-002",
        name: "Cattle Pellet Mix",
        unit: "KG",
        unitSize: 1,
        baseUnitSize: 40,
        distributorPrice: 3900,
        retailerPrice: 3900,
        consumerPrice: 3900,
        isActive: true,
        isDefault: false,
        createdTime: 1780810954318,
        lastUpdatedTime: 0,
      },
    ],
    secondaryUnits: [],
    createdTime: 1780810713329,
    lastUpdatedTime: 1780810836687,
  },
  {
    serial: 100003,
    id: 138,
    code: "POT-001",
    name: "Poultry Starter Mix",
    generic: "",
    description: "",
    categoryId: 28,
    imageUrl:
      "https://api.salesense.logiqbits.com/files/20260607/CcZbheRtXnuIHJgJNOmJEykViGjHUhxohaoeNZgfTZlZIcsDppAAdHSJkyFMIHRnYjYQQuidKEkRjSAJ.png",
    isBlocked: false,
    baseUnit: "kg",
    type: "G",
    vatRate: 0,
    category: {
      id: 28,
      name: "Poultry",
      description: "Poultry",
      parentId: null,
      createdTime: 1780811013706,
      lastUpdatedTime: 0,
    },
    variants: [
      {
        id: 153,
        productId: 138,
        sku: "POT-001",
        name: "Poultry Starter Mix",
        unit: "KG",
        unitSize: 1,
        baseUnitSize: 25,
        distributorPrice: 1750,
        retailerPrice: 1750,
        consumerPrice: 1750,
        isActive: true,
        isDefault: false,
        createdTime: 1780811122588,
        lastUpdatedTime: 0,
      },
    ],
    secondaryUnits: [],
    createdTime: 1780811073874,
    lastUpdatedTime: 0,
  },
  {
    serial: 100004,
    id: 139,
    code: "POT-002",
    name: "Layer Pellets Premium",
    generic: "",
    description: "",
    categoryId: 28,
    imageUrl:
      "https://api.salesense.logiqbits.com/files/20260607/JnHauqVPJuWJmssmfZDyThatHWSZJcmfKswQaXUdkCAWYcBSaCYdboCNfMgsbybdZLfQjrSSpcIKZUKu.png",
    isBlocked: false,
    baseUnit: "kg",
    type: "G",
    vatRate: 0,
    category: {
      id: 28,
      name: "Poultry",
      description: "Poultry",
      parentId: null,
      createdTime: 1780811013706,
      lastUpdatedTime: 0,
    },
    variants: [
      {
        id: 154,
        productId: 139,
        sku: "POT-002",
        name: "Layer Pellets Premium",
        unit: "KG",
        unitSize: 1,
        baseUnitSize: 25,
        distributorPrice: 1550,
        retailerPrice: 1550,
        consumerPrice: 1550,
        isActive: true,
        isDefault: false,
        createdTime: 1780811271331,
        lastUpdatedTime: 0,
      },
    ],
    secondaryUnits: [],
    createdTime: 1780811182177,
    lastUpdatedTime: 0,
  },
  {
    serial: 100005,
    id: 140,
    code: "AQU-001",
    name: "Pre-Starter Fish Feed",
    generic: "",
    description: "",
    categoryId: 29,
    imageUrl:
      "https://api.salesense.logiqbits.com/files/20260607/HsmyVoCbwTMqegVAxaQZuvgKozaydBjjRcfXDeQJUJWTHCFfnyRzjRKfMoZDuemYoZxLJuurAzyLpRbJ.png",
    isBlocked: false,
    baseUnit: "kg",
    type: "G",
    vatRate: 0,
    category: {
      id: 29,
      name: "Aqua",
      description: "Aqua",
      parentId: null,
      createdTime: 1780811342113,
      lastUpdatedTime: 0,
    },
    variants: [
      {
        id: 155,
        productId: 140,
        sku: "AQU-001",
        name: "Pre-Starter Fish Feed",
        unit: "KG",
        unitSize: 1,
        baseUnitSize: 10,
        distributorPrice: 3200,
        retailerPrice: 3200,
        consumerPrice: 3200,
        isActive: true,
        isDefault: false,
        createdTime: 1780811453385,
        lastUpdatedTime: 0,
      },
    ],
    secondaryUnits: [],
    createdTime: 1780811402144,
    lastUpdatedTime: 0,
  },
  {
    serial: 100006,
    id: 141,
    code: "AQU-002",
    name: "Pre-Starter Floating Fish Feed",
    generic: "",
    description: "",
    categoryId: 29,
    imageUrl:
      "https://api.salesense.logiqbits.com/files/20260607/cMJIUuRysWNbkYYyjDNeTVIdgYpfqyQHTjCcTjixWeogjrdnSONtaKvFThIfHmDSugSATiMzrNFOiVsx.jpg",
    isBlocked: false,
    baseUnit: "kg",
    type: "G",
    vatRate: 0,
    category: {
      id: 29,
      name: "Aqua",
      description: "Aqua",
      parentId: null,
      createdTime: 1780811342113,
      lastUpdatedTime: 0,
    },
    variants: [
      {
        id: 156,
        productId: 141,
        sku: "AQU-002",
        name: "Pre-Starter Floating Fish Feed",
        unit: "KG",
        unitSize: 1,
        baseUnitSize: 30,
        distributorPrice: 1650,
        retailerPrice: 1650,
        consumerPrice: 1650,
        isActive: true,
        isDefault: false,
        createdTime: 1780811593562,
        lastUpdatedTime: 0,
      },
    ],
    secondaryUnits: [],
    createdTime: 1780811540567,
    lastUpdatedTime: 0,
  },
];

export const companyId = 10004;
export const paymentTerms = [
  {
    id: 15,
    name: "Credit",
    isActive: true,
    creditPeriodDays: 30,
    companyId: 10004,
    createdTime: 1780811977841,
    lastUpdatedTime: 0,
  },
];

export const distributionPoints = [
  {
    id: 9,
    companyId: 10004,
    managerId: 77,
    code: "WH1",
    name: "Warehouse 1",
    address: "Dhaka",
    createdTime: 1780811961797,
    lastUpdatedTime: 0,
  },
];
